### ISSUE TITLE
Failing to build using hyprpm

### ISSUE THREAD

**Issue by HayyanAzzam** [thrombe/hyprkool#5]
when running the command `hyprpm add https://github.com/thrombe/hyprkool --verbose` I get the following output: 

`➜  ~ hyprpm add https://github.com/thrombe/hyprkool --verbose 
[v] version returned: Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

flags: (if any)

[v] parsed commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91 at branch v0.38.1-b
✔ adding a new plugin repository from https://github.com/thrombe/hyprkool
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] 

 → Cloning https://github.com/thrombe/hyprkool                                                        
✔ cloned                                                                                              
✔ found hyprpm manifest                                                                               
✔ parsed manifest, found 1 plugins:                                                                   
 → hyprkool by thrombe version                                                                        
✔ Hyprland headers OK                                                                                 
 → Building hyprkool                                                                                  
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/new && PKG_CONFIG_PATH="/home/Hayyan/.local/share/hyprpm/headersRoot/share/pkgconfig" make plugin
-- The CXX compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /sbin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /sbin/pkg-config (found version "2.1.1")
-- Checking for modules 'hyprland;pixman-1;libdrm'
--   Found hyprland, version 0.38.1
--   Found pixman-1, version 0.43.4
--   Found libdrm, version 2.4.120
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/hyprpm/new/plugin/build
make[1]: Entering directory '/tmp/hyprpm/new/plugin/build'
[ 50%] Building CXX object CMakeFiles/hyprkool.dir/src/main.cpp.o
/tmp/hyprpm/new/plugin/src/main.cpp: In member function ‘void OverviewWorkspace::render(CBox, timespec*)’:
/tmp/hyprpm/new/plugin/src/main.cpp:283:27: error: ‘class CWindow’ has no member named ‘m_pWorkspace’; did you mean ‘m_iWorkspaceID’?
  283 |             auto& ws = w->m_pWorkspace;
      |                           ^~~~~~~~~~~~
      |                           m_iWorkspaceID
/tmp/hyprpm/new/plugin/src/main.cpp: In member function ‘void OverviewWorkspace::render_window(CWindow*, CBox, timespec*)’:
/tmp/hyprpm/new/plugin/src/main.cpp:304:24: error: ‘class CWindow’ has no member named ‘m_pWorkspace’; did you mean ‘m_iWorkspaceID’?
  304 |         auto o_ws = w->m_pWorkspace;
      |                        ^~~~~~~~~~~~
      |                        m_iWorkspaceID
/tmp/hyprpm/new/plugin/src/main.cpp:306:12: error: ‘class CWindow’ has no member named ‘m_pWorkspace’; did you mean ‘m_iWorkspaceID’?
  306 |         w->m_pWorkspace = m->activeWorkspace;
      |            ^~~~~~~~~~~~
      |            m_iWorkspaceID
/tmp/hyprpm/new/plugin/src/main.cpp:318:12: error: ‘class CWindow’ has no member named ‘m_pWorkspace’; did you mean ‘m_iWorkspaceID’?
  318 |         w->m_pWorkspace = o_ws;
      |            ^~~~~~~~~~~~
      |            m_iWorkspaceID
/tmp/hyprpm/new/plugin/src/main.cpp: In member function ‘void GridOverview::init()’:
/tmp/hyprpm/new/plugin/src/main.cpp:381:31: error: base operand of ‘->’ is not a pointer
  381 |         if (std::regex_match(w->m_szName, overview_pattern)) {
      |                               ^~
/tmp/hyprpm/new/plugin/src/main.cpp:382:43: error: base operand of ‘->’ is not a pointer
  382 |             auto ss = std::istringstream(w->m_szName);
      |                                           ^~
/tmp/hyprpm/new/plugin/src/main.cpp: In member function ‘void GridOverview::render()’:
/tmp/hyprpm/new/plugin/src/main.cpp:417:64: error: ‘struct SRenderModifData’ has no member named ‘enabled’
  417 |         auto o_modif = g_pHyprOpenGL->m_RenderData.renderModif.enabled;
      |                                                                ^~~~~~~
/tmp/hyprpm/new/plugin/src/main.cpp:421:49: error: ‘struct SRenderModifData’ has no member named ‘enabled’
  421 |         g_pHyprOpenGL->m_RenderData.renderModif.enabled = true;
      |                                                 ^~~~~~~
/tmp/hyprpm/new/plugin/src/main.cpp:431:49: error: ‘struct SRenderModifData’ has no member named ‘enabled’
  431 |         g_pHyprOpenGL->m_RenderData.renderModif.enabled = o_modif;
      |                                                 ^~~~~~~
/tmp/hyprpm/new/plugin/src/main.cpp: In function ‘void on_window(void*, SCallbackInfo&, std::any)’:
/tmp/hyprpm/new/plugin/src/main.cpp:498:31: error: base operand of ‘->’ is not a pointer
  498 |         if (std::regex_match(w->m_szName, overview_pattern)) {
      |                               ^~
/tmp/hyprpm/new/plugin/src/main.cpp:499:43: error: base operand of ‘->’ is not a pointer
  499 |             auto ss = std::istringstream(w->m_szName);
      |                                           ^~
make[3]: *** [CMakeFiles/hyprkool.dir/build.make:76: CMakeFiles/hyprkool.dir/src/main.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hyprkool.dir/all] Error 2
make[1]: *** [Makefile:91: all] Error 2
make[1]: Leaving directory '/tmp/hyprpm/new/plugin/build'
make: *** [Makefile:6: plugin] Error 2

✖ Plugin hyprkool failed to build.                                                                    

✔ all plugins built                                                                                   
✔ installed repository                                                                                
✔ you can now enable the plugin(s) with hyprpm enable                                                 
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!                                     
➜  ~ `

**Comment by thrombe** [comment]
it seems like you are using hyprland 0.38.1. but hyprkool plugin only works on 0.39.0 and above.

you can still use hyprkool cli and the daemon. you will be missing [these features](https://github.com/thrombe/hyprkool/blob/fa3294e796fac8cf248dcdfb2a2edb9e14566b21/README.md?plain=1#L15-L16) by not using the plugin tho.
